#!/bin/sh
### BEGIN INIT INFO
# Provides: 		minecraft
# Required-Start: 	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Description: 		Minecraft Server
### END INIT INFO
# INIT Script by wiki.xprog.de
######################################
# Customize values for your needs: "User"; "DIR"
USER="minecraft"
DIR="/home/minecraft/mcserver"
###### Teamspeak 3 server start/stop script ######
case "$1" in
start)
su $USER -c "${DIR}/startscript.sh start"
;;
stop)
su $USER -c "${DIR}/startscript.sh stop"
;;
restart)
su $USER -c "${DIR}/startscript.sh restart"
;;
info)
su $USER -c "${DIR}/startscript.sh info"
;;
*)
echo "Usage: {start|stop|restart|info}" >&2
exit 1
;;
esac
exit 0
