#!/bin/sh
### BEGIN INIT INFO
# Provides: 		sotfdsserver
# Required-Start: 	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Description: 		FOREST Server
### END INIT INFO
# INIT Script by wiki.xprog.de
######################################
# Customize values for your needs: "User"; "DIR"
USER="steamcmd"
DIR="/var/steamcmd/server/sotf"
###### Sons of the forest server start/stop script ######
case "$1" in
start)
su $USER -c "${DIR}/serverstart.sh start"
;;
stop)
su $USER -c "${DIR}/serverstart.sh stop"
;;
restart)
su $USER -c "${DIR}/serverstart.sh restart"
;;
status)
su $USER -c "${DIR}/serverstart.sh status"
;;
*)
echo "Usage: {start|stop|restart|status}" >&2
exit 1
;;
esac
exit 0
