#!/bin/sh
### BEGIN INIT INFO
# Provides: 		srcdsserver
# Required-Start: 	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Description: 		SRCDS01 Server
### END INIT INFO
# INIT Script by wiki.xprog.de
######################################
# Customize values for your needs: "User"; "DIR"
USER="steamcmd"
DIR="/var/steamcmd/server/gmod"
###### Teamspeak 3 server start/stop script ######
case "$1" in
start)
su $USER -c "${DIR}/startserver.sh start"
;;
stop)
su $USER -c "${DIR}/startserver.sh stop"
;;
restart)
su $USER -c "${DIR}/startserver.sh restart"
;;
status)
su $USER -c "${DIR}/startserver.sh status"
;;
*)
echo "Usage: {start|stop|restart|status}" >&2
exit 1
;;
esac
exit 0
